[package]
name = "adventofcode2021"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5"
once_cell = "1.8.0"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "bench_a6"
harness = false
